#define DECLARE_Queue(type)                                                                                                                                                                                                            \
    struct Queue_##type                                                                                                                                                                                                                \
    {                                                                                                                                                                                                                                  \
        type *arr;                                                                                                                                                                                                                     \
        size_t max_size;                                                                                                                                                                                                               \
        size_t back_index;                                                                                                                                                                                                             \
        size_t front_index;                                                                                                                                                                                                            \
        unsigned char rotate;                                                                                                                                                                                                          \
    };                                                                                                                                                                                                                                 \
                                                                                                                                                                                                                                       \
    size_t Queue_##type##_size(struct Queue_##type *self)                                                                                                                                                                              \
    {                                                                                                                                                                                                                                  \
        return (self->back_index < 0 || self->back_index > self->max_size ? 0                                        /* : self->back_index + 1 >= self->front_index ? self->back_index - self->front_index + 1 */                      \
                : self->rotate == 0                                       ? self->back_index - self->front_index + 1 /* : self->front_index > self->back_index + 1  ? self->max_size - (self->front_index - self->back_index + 1) */   \
                                                                          : self->max_size - ((self->back_index >= self->front_index ? self->back_index - self->front_index : self->front_index - self->back_index)));                                                   \
        /* : self->max_size); */                                                                                                                                                                                                       \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type construct_Queue_##type(size_t size)                                                                                                                                                                            \
    {                                                                                                                                                                                                                                  \
        struct Queue_##type self;                                                                                                                                                                                                      \
                                                                                                                                                                                                                                       \
        self.max_size = size;                                                                                                                                                                                                          \
        self.arr = (type *)malloc(sizeof(type) * self.max_size);                                                                                                                                                                       \
                                                                                                                                                                                                                                       \
        self.back_index = -1;                                                                                                                                                                                                          \
        self.front_index = 0;                                                                                                                                                                                                          \
        self.rotate = 0;                                                                                                                                                                                                               \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type construct_Queue_##type##_initialized(type data, size_t size)                                                                                                                                                   \
    {                                                                                                                                                                                                                                  \
        struct Queue_##type self;                                                                                                                                                                                                      \
                                                                                                                                                                                                                                       \
        self.max_size = size;                                                                                                                                                                                                          \
        self.arr = (type *)malloc(sizeof(type) * self.max_size);                                                                                                                                                                       \
                                                                                                                                                                                                                                       \
        self.arr[0] = data;                                                                                                                                                                                                            \
                                                                                                                                                                                                                                       \
        self.back_index = 0;                                                                                                                                                                                                           \
        self.front_index = 0;                                                                                                                                                                                                          \
        self.rotate = 0;                                                                                                                                                                                                               \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type construct_Queue_##type##_initialized_array(type *data, size_t data_size, size_t size)                                                                                                                          \
    {                                                                                                                                                                                                                                  \
        struct Queue_##type self;                                                                                                                                                                                                      \
                                                                                                                                                                                                                                       \
        if (size < data_size)                                                                                                                                                                                                          \
        {                                                                                                                                                                                                                              \
            printf("Input data Overflow!!!");                                                                                                                                                                                          \
            return self;                                                                                                                                                                                                               \
        }                                                                                                                                                                                                                              \
                                                                                                                                                                                                                                       \
        self.front_index = 0;                                                                                                                                                                                                          \
        self.rotate = 0;                                                                                                                                                                                                               \
                                                                                                                                                                                                                                       \
        self.max_size = size;                                                                                                                                                                                                          \
        self.arr = (type *)malloc(sizeof(type) * self.max_size);                                                                                                                                                                       \
                                                                                                                                                                                                                                       \
        for (self.back_index = 0; self.back_index < data_size; self.back_index++)                                                                                                                                                      \
            self.arr[self.back_index] = data[self.back_index];                                                                                                                                                                         \
        self.back_index--;                                                                                                                                                                                                             \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type *destruct_Queue_##type(struct Queue_##type *self)                                                                                                                                                              \
    {                                                                                                                                                                                                                                  \
        if (self->arr)                                                                                                                                                                                                                 \
            free(self->arr);                                                                                                                                                                                                           \
                                                                                                                                                                                                                                       \
        self->arr = NULL;                                                                                                                                                                                                              \
                                                                                                                                                                                                                                       \
        self->max_size = 0;                                                                                                                                                                                                            \
        self->rotate = 0;                                                                                                                                                                                                              \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type *enqueue_Queue_##type(struct Queue_##type *self, type data)                                                                                                                                                    \
    {                                                                                                                                                                                                                                  \
        if (Queue_##type##_size(self) >= self->max_size)                                                                                                                                                                               \
            printf("Queue Overflow!!! for size %d and back %d\n", Queue_##type##_size(self), self->back_index);                                                                                                                        \
        else if (self->back_index >= self->max_size - 1 && self->back_index != (size_t)(-1))                                                                                                                                           \
        {                                                                                                                                                                                                                              \
            printf("ROTATED BY ENQUEUE!!! back >= max_size - 1 = %d, back = %d, front = %d, max_size = %d, rotate = %d\n", self->back_index >= self->max_size - 1, self->back_index, self->front_index, self->max_size, self->rotate); \
            self->arr[self->back_index = 0] = data;                                                                                                                                                                                    \
            self->rotate = 1;                                                                                                                                                                                                          \
        }                                                                                                                                                                                                                              \
        else                                                                                                                                                                                                                           \
            self->arr[++self->back_index] = data;                                                                                                                                                                                      \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type *enqueue_Queue_##type##_array(struct Queue_##type *self, type *data, size_t data_size)                                                                                                                         \
    {                                                                                                                                                                                                                                  \
        if (Queue_##type##_size(self) + data_size > self->max_size)                                                                                                                                                                    \
            printf("Queue Overflow!!! for size %d + Queue_size %d = total_size %d and back %d\n", data_size, Queue_##type##_size(self), Queue_##type##_size(self) + data_size, self->back_index);                                      \
        else                                                                                                                                                                                                                           \
            for (size_t i = 0; i < data_size; i++)                                                                                                                                                                                     \
                enqueue_Queue_##type(self, data[i]);                                                                                                                                                                                   \
        /* if (self->back_index == self->max_size - 1 && self->front_index != 0)                                                                                                                                                       \
            self->arr[self->back_index = 0] = data[i];                                                                                                                                                                                 \
        else                                                                                                                                                                                                                           \
            self->arr[++self->back_index] = data[i];       */                                                                                                                                                                          \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type *dequeue_Queue_##type(struct Queue_##type *self)                                                                                                                                                               \
    {                                                                                                                                                                                                                                  \
        if (Queue_##type##_size(self) < 1)                                                                                                                                                                                             \
            printf("Queue %s Underflow!!!", #type);                                                                                                                                                                                    \
        /* else if (self->front_index == self->max_size - 1 && self->back_index == self->max_size - 1)                                                                                                                                 \
        {                                                                                                                                                                                                                              \
            self->back_index = -1;                                                                                                                                                                                                     \
            self->front_index = 0;                                                                                                                                                                                                     \
        } */                                                                                                                                                                                                                           \
        else if (self->front_index >= self->max_size - 1)                                                                                                                                                                              \
        {                                                                                                                                                                                                                              \
            printf("ROTATED BY DEQUEUE!!! back >= max_size - 1 = %d, back = %d, front = %d, max_size = %d, rotate = %d\n", self->back_index >= self->max_size - 1, self->back_index, self->front_index, self->max_size, self->rotate); \
            self->front_index = 0;                                                                                                                                                                                                     \
            self->rotate = 1;                                                                                                                                                                                                          \
        }                                                                                                                                                                                                                              \
        else                                                                                                                                                                                                                           \
        {                                                                                                                                                                                                                              \
            memset(&(self->arr[self->front_index++]), 0, sizeof(type));                                                                                                                                                                  \
            /* self->front_index++;  */                                                                                                                                                                                                      \
        }                                                                                                                                                                                                                              \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }                                                                                                                                                                                                                                  \
                                                                                                                                                                                                                                       \
    struct Queue_##type *dequeue_Queue_##type##_array(struct Queue_##type *self, size_t dequeue_size)                                                                                                                                  \
    {                                                                                                                                                                                                                                  \
        if (Queue_##type##_size(self) - dequeue_size < 0)                                                                                                                                                                              \
            printf("Queue %s Underflow!!!", #type);                                                                                                                                                                                    \
        else                                                                                                                                                                                                                           \
            for (size_t i = 0; i < dequeue_size; i++)                                                                                                                                                                                  \
                dequeue_Queue_##type(self);                                                                                                                                                                                            \
                                                                                                                                                                                                                                       \
        return self;                                                                                                                                                                                                                   \
    }
