CREATE TABLE cars (
	id SERIAL PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    type VARCHAR(10) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    mileage INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);