"""
DPP Agent – Exporter Module
Exports ProblemSet to multiple formats: JSON, Markdown, plain text.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from .config import OUTPUT_DIR
from .generator import ProblemSet, Problem


# ── Helpers ───────────────────────────────────────────────────────────────────

def _sanitize_filename(name: str) -> str:
    return "".join(c if c.isalnum() or c in "_ -" else "_" for c in name).strip()


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


# ── JSON ──────────────────────────────────────────────────────────────────────

def export_json(ps: ProblemSet, out_dir: Path = OUTPUT_DIR) -> Path:
    fname = out_dir / f"{_sanitize_filename(ps.topic)}_{ps.difficulty}_{_timestamp()}.json"
    payload = {
        "topic": ps.topic,
        "difficulty": ps.difficulty,
        "total_marks": ps.total_marks,
        "generated_at": datetime.now().isoformat(),
        "problems": [
            {
                "id": p.id,
                "type": p.type,
                "difficulty": p.difficulty,
                "question": p.question,
                "options": p.options,
                "answer": p.answer,
                "explanation": p.explanation,
                "hint": p.hint,
                "marks": p.marks,
            }
            for p in ps.problems
        ],
    }
    fname.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return fname


# ── Markdown ──────────────────────────────────────────────────────────────────

def _problem_md(p: Problem, show_answers: bool = False) -> str:
    lines: list[str] = []
    diff_emoji = {"easy": "🟢", "medium": "🟡", "hard": "🔴"}.get(p.difficulty, "⚪")
    type_label = {
        "mcq": "MCQ",
        "short_answer": "Short Answer",
        "long_answer": "Long Answer",
        "fill_blank": "Fill in the Blank",
        "true_false": "True / False",
    }.get(p.type, p.type.upper())

    lines.append(f"### Q{p.id}. [{type_label}] {diff_emoji} _{p.difficulty.capitalize()}_ · **{p.marks} mark{'s' if p.marks > 1 else ''}**")
    lines.append("")
    lines.append(p.question)
    lines.append("")

    if p.options:
        for idx, opt in enumerate(p.options):
            letter = chr(65 + idx)
            lines.append(f"- **{letter})** {opt}")
        lines.append("")

    if p.hint:
        lines.append(f"> 💡 **Hint:** {p.hint}")
        lines.append("")

    if show_answers:
        lines.append(f"<details><summary>✅ Answer</summary>")
        lines.append("")
        lines.append(f"**{p.answer}**")
        if p.explanation:
            lines.append("")
            lines.append(p.explanation)
        lines.append("</details>")
        lines.append("")

    return "\n".join(lines)


def export_markdown(
    ps: ProblemSet,
    out_dir: Path = OUTPUT_DIR,
    show_answers: bool = True,
) -> Path:
    fname = out_dir / f"{_sanitize_filename(ps.topic)}_{ps.difficulty}_{_timestamp()}.md"

    diff_emoji = {"easy": "🟢", "medium": "🟡", "hard": "🔴"}.get(ps.difficulty, "⚪")
    header = f"""# 📚 Problem Set – {ps.topic}

| Field | Value |
|---|---|
| **Difficulty** | {diff_emoji} {ps.difficulty.capitalize()} |
| **Total Problems** | {len(ps.problems)} |
| **Total Marks** | {ps.total_marks} |
| **Generated** | {datetime.now().strftime('%d %b %Y, %H:%M')} |

---
"""
    body = "\n".join(_problem_md(p, show_answers=show_answers) for p in ps.problems)
    footer = "\n---\n*Generated by DPP Agent · Powered by Groq / Ollama qwen3:1.7b*\n"

    fname.write_text(header + body + footer, encoding="utf-8")
    return fname


# ── Plain text ────────────────────────────────────────────────────────────────

def export_text(ps: ProblemSet, out_dir: Path = OUTPUT_DIR) -> Path:
    fname = out_dir / f"{_sanitize_filename(ps.topic)}_{ps.difficulty}_{_timestamp()}.txt"
    lines: list[str] = [
        f"PROBLEM SET – {ps.topic.upper()}",
        f"Difficulty : {ps.difficulty.capitalize()}",
        f"Problems   : {len(ps.problems)}",
        f"Total Marks: {ps.total_marks}",
        "=" * 60,
        "",
    ]
    for p in ps.problems:
        lines.append(f"Q{p.id}. [{p.type}] ({p.difficulty}) – {p.marks} mark(s)")
        lines.append(p.question)
        if p.options:
            for idx, opt in enumerate(p.options):
                lines.append(f"  {chr(65+idx)}) {opt}")
        if p.hint:
            lines.append(f"  Hint: {p.hint}")
        lines.append(f"  Answer: {p.answer}")
        if p.explanation:
            lines.append(f"  Explanation: {p.explanation}")
        lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by DPP Agent")
    fname.write_text("\n".join(lines), encoding="utf-8")
    return fname
